# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.9'

services:

  server:
    image: server
    build:
      context: .
      dockerfile: ./BlazorApp.Server/Dockerfile
    environment:
      ConnectionStrings__Comics:
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: localhost
    ports:
      - 5077:80
      - 7207:443
    depends_on:
      - db
    secrets:
      - source: connection_string
        target: ConnectionStrings__Comics
    volumes:
      - '../../../../.aspnet/https:/https/'
